tap "symfony-cli/tap"

brew "act"
brew "actionlint"
brew "antidote"
brew "autojump"
brew "bat"
brew "composer"
brew "gh"
brew "git-delta"
brew "gitleaks"
brew "hadolint"
brew "glances"
brew "libpq"
brew "lsd"
brew "php"
brew "pre-commit"
brew "shellcheck"
brew "terminal-notifier"
brew "tldr"
brew "uv"
brew "symfony-cli/tap/symfony-cli", trusted: true

cask "beekeeper-studio"
cask "codexbar"
cask "jordanbaird-ice"
cask "orbstack"
cask "pearcleaner"
cask "keeweb"
cask "stats"
brew "dust"
brew "duf"
brew "tree"
brew "tokei"
brew "markdownlint-cli2"
brew "lychee"
