blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Labault/mac-dev-setup#available-documentation
    about: Check the existing documentation before opening an issue.
