#!/bin/bash

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=scripts/lib/command_registry.sh
source "$REPO_DIR/scripts/lib/command_registry.sh"

COMMANDS_DIR="$REPO_DIR/scripts/commands"
COMPLETION_FILE="$REPO_DIR/configs/zsh/completions/_mac"
TEMP_COMPLETION_FILE=""

cleanup() {
  if [ -n "$TEMP_COMPLETION_FILE" ] && [ -f "$TEMP_COMPLETION_FILE" ]; then
    rm -f "$TEMP_COMPLETION_FILE"
  fi
}

trap cleanup EXIT

zsh_quote() {
  value="$1"
  printf "'%s'" "$(printf '%s' "$value" | sed "s/'/'\\\\''/g")"
}

write_completion_content() {
  completion_file="$1"

  {
    printf '%s\n' '#compdef mac'
    printf '%s\n' ''
    printf '%s\n' '# Generated by scripts/generate-zsh-completion.sh; do not edit by hand.'
    printf '%s\n' ''
    printf '%s\n' '_mac() {'
    printf '%s\n' '  local -a commands'
    printf '%s\n' ''
    printf '%s\n' '  commands=('
    printf '    %s\n' "$(zsh_quote 'help:List available commands.')"

    command_registry_build "$COMMANDS_DIR" | while IFS="$COMMAND_REGISTRY_FIELD_SEPARATOR" read -r command_name _command_path command_description; do
      if [ -n "$command_description" ]; then
        completion_entry="$command_name:$command_description"
      else
        completion_entry="$command_name"
      fi

      printf '    %s\n' "$(zsh_quote "$completion_entry")"
    done

    printf '%s\n' '  )'
    printf '%s\n' ''
    printf '%s\n' '  if (( CURRENT == 2 )); then'
    printf "%s\n" "    _describe -t commands 'mac command' commands"
    printf '%s\n' '    return'
    printf '%s\n' '  fi'
    printf '%s\n' ''
    printf '%s\n' "  case \"\${words[2]}\" in"
    printf '%s\n' '    help|--help|-h)'
    printf '%s\n' '      return'
    printf '%s\n' '      ;;'
    printf '%s\n' '    *)'
    printf '%s\n' '      _files'
    printf '%s\n' '      ;;'
    printf '%s\n' '  esac'
    printf '%s\n' '}'
    printf '%s\n' ''
    printf '%s\n' '_mac "$@"'
  } > "$completion_file"
}

write_completion() {
  TEMP_COMPLETION_FILE="$(mktemp "${COMPLETION_FILE}.XXXXXX")"

  write_completion_content "$TEMP_COMPLETION_FILE"

  if [ -f "$COMPLETION_FILE" ] && cmp -s "$TEMP_COMPLETION_FILE" "$COMPLETION_FILE"; then
    rm -f "$TEMP_COMPLETION_FILE"
    TEMP_COMPLETION_FILE=""
    printf 'Completion already up to date: %s\n' "$COMPLETION_FILE"
    return 0
  fi

  mv "$TEMP_COMPLETION_FILE" "$COMPLETION_FILE"
  TEMP_COMPLETION_FILE=""
  printf 'Generated %s\n' "$COMPLETION_FILE"
}

mkdir -p "$(dirname "$COMPLETION_FILE")"
write_completion
